### ISSUE TITLE
Error: DispPropertyFind: inspect Unknown name.

### ISSUE THREAD

**Issue by stanleyxu2005** [durs/node-activex#10]
I build `winax` on Windows 7 (x64) with Node 7.10.0. And then I ran `npm run test`, it passed. I thought everything is fine. 

Now I take a close look into the code.
```
    it("create", function() {
        excel = new ActiveXObject("Excel.Application", { activate: true });
        console.log(excel) // Error: DispPropertyFind: inspect Unknown name.
        console.log(excel.Workbooks) // Error: DispPropertyFind: inspect Unknown name.
    });
```
So the test result shows okay, but actually it is an error message. I have installed Office 2010 on my PC, anything wrong with my usage?

**Comment by konstantin-popov** [comment]
The problem seems to be in the `console.log` call.
In node.js it tries to find the `inspect` method on the object, and fails because this OLE object doesn't have one. If you need to print debug info, you can use `console.log(excel.toString())`.

**Comment by stanleyxu2005** [comment]
Cool. Thank you.
