### ISSUE TITLE
What license is this software?

### ISSUE THREAD

**Issue by tamusjroyce** [durs/node-activex#101]
Could a software license be added? Any terms and conditions is fine. Just hoping this will be open source one day. But if it is not, would you be able to specify that it is closed source? This will help alleviate confusion, as I found my way here through https://github.com/TechQuery/Puppeteer-IE, which is not legally allowed to use this license.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
> 
> Your options:
> 
> Ask the maintainers nicely to add a license. Unless the software includes strong indications to the contrary, lack of a license is probably an oversight. If the software is hosted on a site like GitHub, open an issue requesting a license and include a link to this site, or if you’re bold and it’s fairly obvious what license is most appropriate, open a pull request to add a license.
> 
> Don’t use the software. Find or create an alternative that is under an open source license.
> 
> Negotiate a private license. Bring your lawyer.

**Comment by durs** [comment]
"license": "MIT" (in package.json)
"The MIT License is a permissive free software license" 
This is not enough?

**Comment by tamusjroyce** [comment]
sweet. most projects show it in license.txt but that is more than fine!
