### ISSUE TITLE
Release COM-Object

### ISSUE THREAD

**Issue by Grewamor** [durs/node-activex#11]
Is it possible, to release the COM-Object?

Like in C# [(msdn.microsoft.com)](https://msdn.microsoft.com/de-de/library/system.runtime.interopservices.marshal.releasecomobject(v=vs.110).aspx)
`public static int ReleaseComObject(
	object o
)`

**Comment by durs** [comment]
Try 0.2.4 version
Appended release function
```
var winax = require('winax');
var obj1, obj2, obj3;
winax.release(obj1, obj2, obj3, ...)
``` js
But other temporary objects may be keep references too

**Comment by Grewamor** [comment]
Thx 4 the quick help. But the started prozess is still running.
`const ActiveX = require('winax');

class COM {

    init() {
        var that = this;
        return new Promise(function (resolve, reject) {
            try {
                that.wawi = new ActiveX.Object('XFAKT.App');
                resolve();
            } catch (error) {
                reject(error);
            }
        });


    }

    close() {
        ActiveX.release(this.wawi);
    }
}`

`Promise.all([
    COM.init();
]).then(() => {
    COM.close();
}, e => {
    console.log(e);
});`

In Powershell, the prozess is killed after the end of the scrip:
`$wawi = New-Object -ComObject XFAKT.App;
[System.Runtime.Interopservices.Marshal]::ReleaseComObject($wawi)  
`
