### ISSUE TITLE
Q: How to obtain a running instance of Excel (Marshal.GetActiveObject?)

### ISSUE THREAD

**Issue by kenklin** [durs/node-activex#118]
I'm not familiar with Excel programming but have read https://learn.microsoft.com/en-us/office/vba/api/overview/excel and managed to use `winax` to launch a **new instance** of Excel with a supplied filename `f` and manipulate its worksheet's cells with code like this:
```
    application = new winax.Object("Excel.Application", {activate: true});

    const updateLinks = 0;
    const readOnly = false;
    workbook = application.Workbooks.Open(f, updateLinks, readOnly);

    <get worksheets and manipulate its cells>
```

My question is how to access an **already running** instance of Excel using `winax`?  After some Googling, it seems I may need to somehow access [Marshal.GetActiveObject](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getactiveobject?view=netframework-4.8) ?  If so, if you could point me to sample code using `winax`, I'd be grateful - thanks in advance.

**Comment by durs** [comment]
That's right, when using the **activate** option, the code is called:

    CComPtr<IUnknown> unk;
    hrcode = GetActiveObject(clsid, NULL, &unk);
    if SUCCEEDED(hrcode) hrcode = unk->QueryInterface(&disp);

**Comment by somanuell** [comment]
To access an already running instance of Excel you must use the "getobject" option, not the "activate" one.
Code sample:

`var	oApp = new winax.Object("Name of the File in the ROT", {getobject: true});`

**Comment by kenklin** [comment]
@somanuell Thanks for the JS-side example!  Closing.

**Comment by kenklin** [comment]
Aside - my Javascript code has been migrated to resides in an [Excel Add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-overview).
