### ISSUE TITLE
Error: DispPropertyGet: Invalid number of parameters

### ISSUE THREAD

**Issue by xK0ff33** [durs/node-activex#12]
Firstly, thanks @durs for the library, it's exactly what I needed, great job!

I have a problem with calling any function that takes at least one parameter, as I'm getting `Error: DispPropertyGet`.

```javascript
const winax = require('winax')
const myAutom = new winax.Object('ControlCenter.Automation')
const playback = myAutom.Playback
let d = playback.SelectedDestination // works fine, returns 1 in the example
let m = playback.CurrentCamera(d) // fails with DispPropertyGet error
```

When inspecting the `playback` object in WebStorm (and from internal docs), I can see that the method should take only one argument.

![WebStorm](https://user-images.githubusercontent.com/8126512/28493865-b8353640-6f16-11e7-9595-ce9128f8e4e6.png)
![Internal Documentation](https://user-images.githubusercontent.com/8126512/28493876-e1590fec-6f16-11e7-82c1-2431fbd73200.png)

`Error: DispPropertyGet: CurrentCamera Invalid number of parameters.`

Any ideas? Similar code works fine using C#.

**Comment by durs** [comment]
Try new 1.0.2 version, which fixed PropertyGet with arguments.
Or disable typeinfo : new winax.Object('ControlCenter.Automation', { type: fase });

**Comment by xK0ff33** [comment]
Thanks, works fine now with 1.0.2, only had to do a couple of adjustments to get the value of an object through `obj.__value`.

**Comment by durs** [comment]
__value for debugging purposes, it's better to use valueOf()

**Comment by durs** [comment]
Otherwise it does not work, valueOf is called automatically by javascript
for some operations, eg arithmetic,
but an exact comparison === will not work, because this is actually an
object.
