### ISSUE TITLE
update docx toc failed in word but succeeded in wps

### ISSUE THREAD

**Issue by lianyzhou** [durs/node-activex#120]
First Thanks to Great job on creating node-activex，this makes more possibility for nodejs application.

Recently I encoutered a requirement of updating docx's table of contents，and I found node-activex. 

Currently I cound did it by using WPS（https://www.wps.com/）， but when using microsoft word， it report a error.

![image](https://user-images.githubusercontent.com/6295633/223305977-ce45813b-7f1f-4388-99a9-0a12e097186e.png)

Here's my code
`
var winax = require("winax");
var word;
let doc = null;
try {
    // word = new winax.Object("KWPS.Application");
    word = new winax.Object("Word.Application");
    doc = word.documents.open("E:/1.docx")
    doc.TablesOfContents[1].UpdatePageNumbers();
    doc.save();
} catch(e) {
    console.log('encoutered exception', e);
} finally {
    try {
        doc && doc.close();
    } catch(e){
        console.log('doc.close error');
    }
    
    try {
        word && word.quit();
    } catch(e){
        console.log('word.quit error');
    }
   
    try {
        word && winax.release(word);
    } catch(e){
        console.log('winax.release error');
    }
}
`

the word api i found here: 
[https://learn.microsoft.com/zh-tw/dotnet/api/microsoft.office.interop.word.tableofcontents.updatepagenumbers?view=word-pia#microsoft-office-interop-word-tableofcontents-updatepagenumbers](url)

**Comment by lianyzhou** [comment]
My Computer Environment:

win32 10.0.19044(x64) Windows 10 Home China 21H2
Windows Feature Experience Pack 120.2212.4190.0

nodejs version: v16.14.0
winax version: 3.3.4

**Comment by lianyzhou** [comment]
here's my docx file
[1.docx](https://github.com/durs/node-activex/files/10904963/1.docx)

**Comment by lianyzhou** [comment]
console.log(doc.TablesOfContents[1]) and i found there's no UpdatePageNumbers function for word
![image](https://user-images.githubusercontent.com/6295633/223309590-826c6b05-0903-44ab-89bc-0862e46e7b83.png)

**Comment by durs** [comment]
doc.TablesOfContents is not array and similar doc.TablesOfContents.Item is not array,
so you need to call Item as method: doc.TablesOfContents.Item(1).UpdatePageNumbers()

**Comment by lianyzhou** [comment]
@durs  Thanks a lot, doc.TablesOfContents.Item(1).UpdatePageNumbers() will work
