### ISSUE TITLE
How to attach to an existing IDispatch pointer

### ISSUE THREAD

**Issue by somanuell** [durs/node-activex#122]
Hi durs,
I have a situation where an Excel is not correctly saved in the ROT, but I think I can retrieve an IDispatch* by other means (using an MSAA technique). Could I then somehow "inject" the IDispatch pointer into winax?

**Comment by durs** [comment]
Hi, found this example:

```
// Create COM object from JS
var obj = new winax.Object({
    test: function(v) { return v*2; }
});

// Convert COM IDispatch pointer to Variant array
var varr = new winax.Variant(obj, 'uint8[]');

// Convert Variant array to JS array address bytes
var arr = new Uint8Array(varr.valueOf());
console.log(arr);

// Create new COM object from IDispatch pointer (address bytes)
var obj2 = new winax.Object(arr);

// Call test method
console.log(obj2.test(2));
```

**Comment by durs** [comment]
Ok, I'll make a release, while I don't plan to change anything else

**Comment by somanuell** [comment]
Hi, again. When I built winax with npm i against node 14.18.3 in january 2022, I got a node_activex.node of approx 185 kB. Today when I npm i winax against node 14.20.0 I get a node_activex.node of 560 kB! What am I missing here?

**Comment by durs** [comment]
I don't know, last release in my environment 240 Kb with Node 18.13 and Visual Studio 2022 (v143)

**Comment by somanuell** [comment]
What is your build method?

**Comment by durs** [comment]
npm install
then tried rebuild binding.sln but got the same result

**Comment by somanuell** [comment]
Same here! npm install ==> node_activex.node is 544 KB
rebuild binding.sln ==> node_activex.node is 544 KB....
node --version ==> v14.20.0
Visual Studio 2022 (v143)
I AM LOST!
