### ISSUE TITLE
Converting JavaScript string to C++ BSTR

### ISSUE THREAD

**Issue by xK0ff33** [durs/node-activex#13]
Hi, I have a ActiveX property that takes in BSTR as an argument that  doesn't seem to work properly in `node-activex`.

Docs:
```
NvrFromIpAddress  ([in] BSTR IpAddress) [get]
Property to get an NVR by IP Address.
```
NodeJS:
```javascript
let nvr = myAutom.Nvrs.NvrFromIpAddress['192.168.1.9'] // returns undefined
```
C#:
```csharp
var nvr = myAutom.Nvrs.NvrFromIpAddress["192.168.1.9"]; // returns nvr object
```

Any ideas? I've tried couple other functions/properties that take BSTR as an argument and none work correctly.

**Comment by durs** [comment]
What if with round brackets

let nvr = myAutom.Nvrs.NvrFromIpAddress('192.168.1.9');


2017-07-30 1:13 GMT+03:00 Kamil Wojtczyk <notifications@github.com>:

**Comment by xK0ff33** [comment]
I've tried that as well and returns:
```
Error: DispInvoke: NvrFromIpAddress Member not found.
```

**Comment by durs** [comment]
Try new 1.0.3 version with property get fix

**Comment by xK0ff33** [comment]
Thank you so much @durs, works perfectly! 😃
