### ISSUE TITLE
Winax crashes when there is no ActiveX component installed in the system. Try catch do not help.

### ISSUE THREAD

**Issue by nickolayl** [durs/node-activex#18]
Hi!

Thank you for the useful library.

Unfortunately I am experiencing troubles at runtime when trying to call to 
`var con = new ActiveXObject('MyRequiredActiveXComponentName');`
My Electron application that uses node-activex crashes if `MyRequiredActiveXComponentName` does not installed on the client computer.
If I install and register the ActiveX component `MyRequiredActiveXComponentName` - things work well.

I tried to try catch the exception but the error seems to be not a JavaScript exception that I can catch. Catch simply never called. The Node process just crashes.

I am looking for the library update or the workaround. Is there any way to get the information whether the `MyRequiredActiveXComponentName` installed on that particular machine?

**Comment by durs** [comment]
It's very strange, for test run javascript:

var test;
try {
test = new ActiveXObject('la-la-la');
}
catch(e) {
console.log('Exception: ' + e.message);
return;
}


Result
*Exception: CreateInstance: la-la-la Invalid class string*



2017-11-19 1:04 GMT+03:00 nickolayl <notifications@github.com>:

**Comment by nickolayl** [comment]
@durs thanks! This worked well.
