### ISSUE TITLE
Converting JavaScript array to Variant()

### ISSUE THREAD

**Issue by godunov** [durs/node-activex#19]
Hello!
This example doesn't seem to work.

 `let excel = new ActiveXObject("Excel.Application", { activate: false })
excel.Visible = true
let workbook = excel.Workbooks.Add()
let sheet = workbook.Worksheets.Item(1)

// Method 1
// not working
let range = sheet.Range("A1")
range = range.Resize(1, 4)
range.Value = 1 // works
range.Value = [1, 2, 3, 4] // error

// Method 2
// dict.Items returns Variant()
// works in vba
var dict = new ActiveXObject("Scripting.Dictionary")
dict.Add("0", 0)
dict.Add("1", 1)
dict.Add("2", 2)
dict.Add("3", 3)

sheet.Range('A2').Resize(1, 4).Value = dict.Items // Error`

How to set Excel.Range(..).Value to variable of 'Variant()' type ?
Unless it is this way the script works very slowly.
As i understand Excel.Range(..).Value gets Variant() and converts it into SAFEARR.
Maybe this error occurs because your library lacks function arrayToVariant()?

**Comment by durs** [comment]
This problems fixed in new 1.0.4 version

**Comment by somanuell** [comment]
Hi,

Writing "horizontally" works fine.
`comActiveSheet.Range("C1:F1").Value = [ 1, 2, 3, 4 ];`

but I can't find the correct syntax to use for writing "vertically"
`comActiveSheet.Range("C1:C4").Value = ?????;`

@godunov Could you help?
