### ISSUE TITLE
Exception calling MS-word's Document.SaveAs Method (works in vbs)

### ISSUE THREAD

**Issue by Gei0r** [durs/node-activex#20]
Hi,

with the following script:

    const winax = require('winax');
    
    let app = new winax.Object('Word.Application');
    let doc = app.Documents.Open("D:\\test.docx");
    doc.SaveAs("D:\\test.pdf", 17 /* wdFormatPDF */); 
    doc.Close();
    app.Quit();

I get the following error:

    C:\Users\A\Documents\WordBridge2\index2.js:5
    doc.SaveAs("D:\\test.pdf", 17 /* wdFormatPDF */);
        ^
    
    Error: DispInvoke: SaveAs Ausnahmefehler des Servers.

    
        at Object.<anonymous> (C:\Users\A\Documents\WordBridge2\index2.js:5:5)
        at Module._compile (module.js:641:30)
        at Object.Module._extensions..js (module.js:652:10)
        at Module.load (module.js:560:32)
        at tryModuleLoad (module.js:503:12)
        at Function.Module._load (module.js:495:3)
        at Function.Module.runMain (module.js:682:10)
        at startup (bootstrap_node.js:191:16)
        at bootstrap_node.js:613:3

("Ausnamefehler des Servers" is German, means something like "exception in the server").

But it works with the following vbs script:

    set app = CreateObject("Word.Application")
    set doc = app.Documents.Open("D:\\test.docx")
    doc.SaveAs "D:\\test.pdf", 17
    doc.Close()
    app.Quit()

when executed as `cscript index.vbs`.

Also, `doc.SaveAs("D:\\test.pdf");` (without the 17) works with winax.

So there seems to be some sort of problem with the parameter, maybe because it's actually an enum. Any ideas?

**Comment by durs** [comment]
This problem fixed in new 1.0.4 version

**Comment by Gei0r** [comment]
wow, that was quick!

I can confirm that it works. Thank you.
