### ISSUE TITLE
Using existing activeXObject

### ISSUE THREAD

**Issue by winrono** [durs/node-activex#21]
I'm trying to use opened instance of Excel, but didn't find a way to do it with this library. Is it supported? If yes, please provide example :)

**Comment by winrono** [comment]
@durs thanks for quick reply. unfortunately it doesn't work.

I'm using simplest piece of code:

```
require('winax');

var xl = new ActiveXObject('Excel.Application', {
    activate: true
});

xl.Visible = true;
```

**Comment by winrono** [comment]
Btw it seems to be issue specific to Excel as it works perfectly fine for 'Word.Application'

**Comment by durs** [comment]
Multiple instances of Excel can be runned background, see processes in task manager

**Comment by winrono** [comment]
@durs, thanks a lot, probably had zombie Excel process or something like this. Now it works fine
