### ISSUE TITLE
Can't able to access the Registered dll class files.

### ISSUE THREAD

**Issue by Antony-jeban** [durs/node-activex#23]
I register a dll using `regsvr32 /n /i:user wgssSTU.dll`  and the dll is registered in **HKEY_USERS** path,
I can't able to access the dll classes using winax.
`  require('winax');
 var test = new ActiveXObject("WacomGSS.STU.UsbDevices");
 `
While running the above code i'm getting **Class not registered** Error
But it is registered.

**Comment by durs** [comment]
It`s WinAPI error on call 
CLSIDFromProgID("WacomGSS.STU.UsbDevices", &clsid)
or 
CoCreateInstance(clsid, nullptr, CLSCTX_INPROC_SERVER | CLSCTX_LOCAL_SERVER)
Cscript worked successfully?

**Comment by Antony-jeban** [comment]
No, I haven't tried it with Cscript. 
but `var test = new ActiveXObject("WacomGSS.STU.UsbDevices");`  This code is working fine with 
Internet Explorer Version 11, but the above code is throwing error while accessing it using Electron.

**Comment by jprules321** [comment]
I know this is old but I had the same problem and it ended up beeing that my DLL was 32bits and I needed to launch electron in 32 bit since a x64 process can't access x86 dlls.

**Comment by jprules321** [comment]
Also, if your DLL is indeed 32bits mobe it to sysWOW64 and register it using the regsvr32 in that folder.

**Comment by Antony-jeban** [comment]
> I know this is old but I had the same problem and it ended up beeing that my DLL was 32bits and I needed to launch electron in 32 bit since a x64 process can't access x86 dlls.

Yea this seems to be the issue i think. I've found out a different solution for my problem.

Thanks for the reply.

Closing this issue since it is not an actual issue with `node-activex`.
