### ISSUE TITLE
[Bug] IE object reference incorrect

### ISSUE THREAD

**Issue by TechQuery** [durs/node-activex#25]
```JavaScript
var IE = new ActiveXObject('InternetExplorer.Application');
IE.Visible = false;
IE.Navigate('github.com');

setTimeout(function ready() {

    if ((! IE.Busy)  ||  (IE.Busy.valueOf() !== false))
        return  setTimeout( ready );

    var document = IE.Document;
    var Div = document.createElement('div');
    document.body.appendChild( Div );
});
```
The script above will throw `Error: DispInvoke: appendChild Error 0x80020101`.

I think, maybe `winax` failed to convert JS object in V8 to COM+.

**Comment by durs** [comment]
Error fixed, see new 1.0.8 version

**Comment by TechQuery** [comment]
Cool !  So fast you are !  Thanks a lot !

But, I'm wondering, although the version of IE is 11, the **COM+ interface** has only *IE 8- API*.

**Comment by durs** [comment]
Yes, it also upsets me, I have to use for managing a web page through COM (invoke client javascript)
<meta http-equiv="X-UA-Compatible" content="IE=8"/>

**Comment by TechQuery** [comment]
You can try [Puppeteer-IE](https://techquery.github.io/Puppeteer-IE/) which I'm developing~
