### ISSUE TITLE
Get CURRENCY variable

### ISSUE THREAD

**Issue by alfarobotics** [durs/node-activex#28]
I'm trying to get a property with a "currency" type from a dll. But the constructor assigns __value = undefined
`var sum1 = new winax.Variant( con.Summ1, 'int64' );
        console.log( con.Summ1 );`
Console:
`Variant { [__type]: 'int64', [__value]: undefined }`
[type definition link](https://msdn.microsoft.com/en-us/library/aa909109.aspx)

**Comment by durs** [comment]
Hi, try 1.0.9 version, appended support currency and decimal types

2018-04-12 10:54 GMT+03:00 alfarobotics <notifications@github.com>:

**Comment by alfarobotics** [comment]
Thank you very much! It works.
