### ISSUE TITLE
What is the usage of dependency webworker-thread?

### ISSUE THREAD

**Issue by stanleyxu2005** [durs/node-activex#30]
Dear Developer,

There is a dependency `webworker-thread` in the package. I failed to build it but it seems no harm to me. I'd like to know, what is the usage of this package. Can we remove it from the package.json?
https://github.com/durs/node-activex/blob/895670e61811d95c005dd3004239a76738dad230/package.json#L31-L33

**Comment by durs** [comment]
Well, thanks

вс, 10 Июн 2018 г., 6:39 Qian Xu (Stanely) <notifications@github.com>:

**Comment by stanleyxu2005** [comment]
Thank you for the change
