### ISSUE TITLE
Getting extended error info from ActiveXObject

### ISSUE THREAD

**Issue by Avrohom** [durs/node-activex#33]
Hi,

I am using Winax. Works fine. When error occurs on a dispatched task I can catch that error. The info available to me is basically a string message describing the error. I was wondering if it would be possible to get additional error info, such as Error codes that the activeX objects exposes.

**Comment by Avrohom** [comment]
Hi Yuri,

Many thanks for addressing this issue on the last release. 

But I am still very sorry to tell you that this has not solved my problem. 

What 'errno' contains is the HRESULT of the exception. However the COM object I am using will always issue the same HRESULT value for all different exception types. What differs is the 'COMException.ErrorCode' number. 
Any chance of getting this one, please?

**Comment by durs** [comment]
Try 1.0.12 version,
I am appended additional Error fields:  code, scode, description and source from tagEXCEPINFO structure, returned by IDispatch::Invoke method

**Comment by durs** [comment]
Try 1.0.12 version,
I am appended additional Error fields: code, description and source from tagEXCEPINFO structure, returned by IDispatch::Invoke method

**Comment by Avrohom** [comment]
Hi Yuri,

WOW! How fantastic!? 

Really Great.  Works Superb. Tried and Tested.

So many thanks.
