### ISSUE TITLE
Node crashes on null property of received object.

### ISSUE THREAD

**Issue by Avrohom** [durs/node-activex#36]
Hi, 

On Node (I am actually using Node Webkit NW.js) when getting back results from a ActiveX object I have one of the properties of the returned object that may or may not be null.

I don't even get a chance for null-checking. As soon I try to access it be it either via code or the debugger the application crashes brutally.

**Comment by durs** [comment]
Please send me an example of javascript that causes an application crash

пт, 17 авг. 2018 г. в 18:47, Avrohom <notifications@github.com>:

**Comment by Avrohom** [comment]
Hi Yuri, 

Thanks for your feedback.

Here is the code:

`function getQB_info() {
    require('winax')

    const session_manager = new ActiveXObject('QBFC13.QBSessionManager.1');
    const ENOpenMode = Object.freeze({ 'omSingleUser': 0, 'omMultiUser': 1, 'omDontCare': 2 })
    const appName = "AmazonConnector"
    const appId = ''
    function doRequestAndGetResult(reqSet) {
        var responseMsgSet = session_manager.doRequests(reqSet);
        var status = responseMsgSet.ResponseList.GetAt(0);
        var statusCode = status.StatusCode;
        var statusMessage = status.StatusMessage;

        if (statusCode !== 0) {
            var message = 'Quickbooks Error: "' + statusMessage + '"'
            var err = new Error(message)
            err.code = statusCode
            throw err
        }

        return responseMsgSet.ResponseList.GetAt(0).Detail
    }

    session_manager.OpenConnection(appId, appName)
    var result = session_manager.BeginSession('', ENOpenMode.omDontCare)

    try {
        var requestSet = session_manager.CreateMsgSetRequest("UK", 12, 0)

        requestSet.ClearRequests();
        var companyQuery = requestSet.AppendCompanyQueryRq()
        var companyRet = doRequestAndGetResult(requestSet)
        console.log(companyRet.CompanyName.GetValue())

        console.log(companyRet.Address.Addr1.GetValue())

        // companyRet.Address.Addr2 == null. or 'undefined' / not declared doesn't exist or whatever. 
        // The following instructions or If hovering on that variable whilst debugging will crash the whole application
        if (typeof companyRet.Address.Addr2 !== 'undefined' && companyRet.Address.Addr2 !== null)
            console.log(companyRet.Address.Addr2)

        if (companyRet.Phone !== null)
            console.log(companyRet.Phone.GetValue())

        if (companyRet.Email)
            console.log(companyRet.Email.GetValue())

        if (companyRet.EIN !== null)
            console.log(companyRet.EIN.GetValue())

        // companyRet.SSN == null. or 'undefined' / not declared doesn't exist or whatever.
        // The following instructions or If hovering on that variable whilst debugging will crash the whole application
        if (typeof companyRet.SSN !== 'undefined' && companyRet.SSN !== null)
            console.log(companyRet.SSN.GetValue())
    }
    catch (e) {
        alert(e)
    }

    session_manager.EndSession()
    session_manager.CloseConnection()
}`

**Comment by durs** [comment]
I`m fixed null pointers in variants, try winax@1.0.14

**Comment by Avrohom** [comment]
Wow! Excellent staff!!!

I have tried and tested. Works wonderfully. So Great!

Many thanks!!!!
