### ISSUE TITLE
can't install 

### ISSUE THREAD

**Issue by creatworld** [durs/node-activex#38]
i have installed python and set environment variable, but still report error.

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\creatworld\AppData\Local\Prgrams\Python\Python35\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\NodeJs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\NodeJs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\NodeJs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "D:\\NodeJs\\node.exe" "D:\\NodeJs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\项目\Vueone\20开发区\03代码\vueone\跨平台\nwjs-xpsp3\vueone\node_modules\winax
gyp ERR! node -v v8.11.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN vueone@1.0.0 No description
npm WARN vueone@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! winax@1.0.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the winax@1.0.14 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\creatworld\AppData\Roaming\npm-cache\_logs\2018-10-16T03_41_39_290Z-debug.log

**Comment by Estradiaz** [comment]
My guess is node-gyp still not supports Python > 2?

**Comment by durs** [comment]
- python (v2.7 recommended, v3.x.x is *not* supported)

https://github.com/nodejs/node-gyp

вт, 16 окт. 2018 г. в 23:08, Samuel Ueberle <notifications@github.com>:
