### ISSUE TITLE
How to interact with function expecting SAFEARRAY**?

### ISSUE THREAD

**Issue by jeffvandyke** [durs/node-activex#42]
I'm a bit under the gun, but I'm wondering how to call a COM function that expects a SAFEARRAY** as an out parameter to send data from COM to JavaScript? Many thanks, and great work on this library!

**Comment by durs** [comment]
Hi, maybe
  var arr = new Variant([], 'byref');
  comobj.method(arr);
but memory leak is possible

ср, 16 янв. 2019 г. в 18:29, Jeff VanDyke <notifications@github.com>:

**Comment by jeffvandyke** [comment]
Thanks for the reply; unfortunately didn't work for our program's api. The error is:
```
{ [Error: DispInvoke: MethodName Type mismatch.
] errno: -2147352571 }
```
From a C# program, it works when passing in a `ref array` where array is a normal C# array that has been reserved to the size the interface expects. It's not as critical now, but it does support the use case of passing large binary data around without many allocations, so maybe it'd be a nice feature to have for those cases.

**Comment by jeffvandyke** [comment]
I think I'll close this issue. It'd still be nice to have, but we don't need this feature for what we're doing anymore.
