### ISSUE TITLE
Please, update NODE_MODULE_VERSION for Electron above 4.0.3

### ISSUE THREAD

**Issue by Den2016** [durs/node-activex#48]
When using Electron above 4.0.3, an error occurs.
```
Error: The module '\\? \C:\project\node_modules\winax\build\Release\node_activex.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69.
```
Electron [uses ](https://github.com/electron/electron/commit/9f0c410bc6ac5f479740f2503a81f238af4c9a44)NODE_MODULE_VERSION 69 since version 4.0.4, npm rebuild winax --runtime = electron --target = 4.0.4 (and higher) does not take this into account. Please fix it.

**Comment by durs** [comment]
How to do it? Nowhere in the module  NODE_MODULE_VERSION  is not specified.
Apparently determined automatically when calling "node-gyp configure"

чт, 18 апр. 2019 г. в 14:32, Denis <notifications@github.com>:

**Comment by Den2016** [comment]
Yes, this is Node.js and Electron conflict. Winax not guilty )) sorry )
