### ISSUE TITLE
[Question] Doesn't this project be enrolled in npm ?

### ISSUE THREAD

**Issue by woosungchu** [durs/node-activex#51]
How can I load this released version to my private project?

```
// not working
npm install node-activex
npm install node_activex
```

both doesn't work and cannot find in [npm](https://www.npmjs.com/search?q=activex)

**Comment by durs** [comment]
npm install winax
https://www.npmjs.com/package/winax


пн, 8 июл. 2019 г. в 03:38, woosungchu <notifications@github.com>:

**Comment by woosungchu** [comment]
thank you, I didn't notice at all...
