### ISSUE TITLE
Passing activeXobject to another one. Type mismatch

### ISSUE THREAD

**Issue by avin** [durs/node-activex#6]
Trying to pass activeX object as an argument and got Type mismatch error of lib.
```
const crs1 = new ActiveXObject('ZuluLib.CRS');
crs1.InitByCode("EPSG:4326");
const crs2 = new ActiveXObject('ZuluLib.CRS');
crs2.InitByCode("EPSG:3857");

crs1.GetConvertPoint(60, 30, crs2); //<< Type mismatch of `crs2`
```
Original: https://www.politerm.com/zuludoc/zuluax/CRS_GetConvertPoint.htm

Is there any option to do it right way?

**Comment by durs** [comment]
Try new version, corrected filling arguments and changed method valueOf()
