### ISSUE TITLE
Objects stay pinned due to valueOf & toString methods implementation

### ISSUE THREAD

**Issue by ghtmpn** [durs/node-activex#60]
Hello.

**Short version:** my COM objects are not released even with `global.gc()` call.

**Long version**
**winax:** 1.12.0
**node:** v10.15.1
**windows:** 10 LTSC 64-bit
**msvc**: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe

## Expecting
```javascript
// test.js
// node --expose-gc test.js

function work() {
  var app = new ActiveXObject('V1CEnterprise.Application')
  app.Initialize(app.RMTrade, '<conn_str>', 'NO_SPLASH_SHOW')
  var sel = app.CreateObject('Справочник.Клиенты')
  sel.ВыбратьЭлементы()
  sel.ПолучитьЭлемент()
  var id = sel.Код
  id.valueOf // no call, just 'get'
}
work()
gc()
```
This code should release all references to wrapped COM objects (namely app, Initialize, RMTrade, CreateObject, sel, ВыбратьЭлементы, ПолучитьЭлемент and Код (=== id)) and co-process should exit.

**But** it does release all of them except **Код**. Rebuilding winax with NODE_DEBUG enabled and additional debug `cout`s confirms this.

If I comment-out this line though:
```javascript
  // id.valueOf // no call, just 'get'
```
then it does release everything correctly. The same is true for `.toString`.
(`.__proto__` or `.__id` do not cause the issue)

---
## Why does it happen
I hunted it down to this part of winax:
https://github.com/durs/node-activex/blob/master/src/disp.cpp#L528
```cpp
void DispObject::NodeGet(Local<Name> name, const PropertyCallbackInfo<Value>& args) {
  ...
  else if (_wcsicmp(id, L"valueOf") == 0 || !*id) {
    Local<Function> func;
    if (FunctionTemplate::New(isolate, NodeValueOf, args.This())->GetFunction(ctx).ToLocal(&func)) {
      args.GetReturnValue().Set(func);
    }
  }
  else if (_wcsicmp(id, L"toString") == 0) {
    Local<Function> func;
    if (FunctionTemplate::New(isolate, NodeToString, args.This())->GetFunction(ctx).ToLocal(&func)) {
      args.GetReturnValue().Set(func);
    }
  }
```
I'm not familiar with Node wrappers, but it seems to be equivalent to `return valueOf.bind(this)`.
If I change the line with `FunctionTemplate::New` call like this:
```cpp
    Local<Value> v; // empty value
    if (FunctionTemplate::New(isolate, NodeValueOf, v)->GetFunction(ctx).ToLocal(&func)) {
```
then my snippet above works as expected. I think that at c++ side Node either caches or forgets to garbage-collect functions that are bound at c++ level, and that prevents object references to drop to zero. As `valueOf` and `toString` are called by virtually everything in Node, including operators and console.log, any `sel.*` values I use in expressions and/or logs are pinned forever.

Node.js itself doesn't care to call finalizers at exit. Without `global.gc()` it doesn't release anything, no matter what. With `global.gc()` it does call finalizers for regular unreachable objects, but it **never** does that for these bound `valueOf` and `toString` bound functions.

---
## Why doesn't it happen for everyone
Everyone is using Excel/Office. Office is known to remain running after COM disconnect, so virtually everyone calls `Excel.Application.Quit()` after they are done with it, and that terminates its process by force, invalidating COM handles. Given how rare COM is used today, minus Excel uses, it is pretty plausible that no one met this issue before.

---
## Solution?
I think that force-binding `this` is unnecessary in `DispObject::NodeGet`, since Node will always call `valueOf` and `toString` with correct `this`. The only potential problem I see is that someone could do something like:
```javascript
var valueOf = sel.Код.valueOf
valueOf()
```
and (maybe) get their access violation.

Thanks for a nice connector, Yuri!

**Comment by durs** [comment]
Thanks for the detailed problem statement.
Posted 1.13 version without binding this.
valueOf() call throw exception DispInvalid

**Comment by ghtmpn** [comment]
Thank you very much for a quick response and the fix!

I can confirm that 1.13, as a drop-in replacement for custom changes I made before, works as expected on a full project.

I see that you fixed much more places than I was aware of, specifically in VariantObject::NodeGet. But I cannot test them, because V1CEnterprise.Application seems to not generate Variants.
