### ISSUE TITLE
New Electron 8.2.0 Rebuild not building...

### ISSUE THREAD

**Issue by Cupidazul** [durs/node-activex#69]
Recommended patch in utils.h:

-#if V8_MAJOR_VERSION >= 7
-#if V8_MINOR_VERSION > 0	// node v11.13
+#if (V8_MAJOR_VERSION > 7) || (V8_MAJOR_VERSION == 7 && V8_MINOR_VERSION >= 1)
 	#define NODE_BOOL_ISOLATE
 #endif
-#endif

based on:
https://github.com/pmed/v8pp/commit/f2127d300592fd1644dae7be5a4e15cb92b00331

**Comment by durs** [comment]
Thanks, accepted
