### ISSUE TITLE
VT_I8/VT_UI8 support

### ISSUE THREAD

**Issue by kuseni** [durs/node-activex#77]
Please, add VT_I8/VT_UI8 support. Something like 
```
case VT_I8:
  return Number::New(isolate, by_ref ? *v.pllVal : v.llVal);
...
case VT_UI8:
  return Number::New(isolate, by_ref ? *v.pullVal : v.ullVal);
```
in static Local<Value> Variant2Array2(Isolate *isolate, const VARIANT &v) in utils.cpp

**Comment by durs** [comment]
ok, see winax@1.19.0
but long values may be truncated to double, int64 values node js not
supported

чт, 21 мая 2020 г. в 20:47, kuseni <notifications@github.com>:

**Comment by kuseni** [comment]
No problem, safe -(2^53 - 1) .. 2^53 - 1 usually is enough (and much better than nothing). Thanks!
