### ISSUE TITLE
 err in electron-vue on windows

### ISSUE THREAD

**Issue by lianshengxing** [durs/node-activex#8]
i required 'winax' in electron-vue on windows,and it threw an err that "can not find module './build/Release/node_activex"

**Comment by durs** [comment]
It's a binary addon, need VC++2015 or later and build throw node-gyp.
For example, execute commands in winax folder
node-gyp configure
node-gyp build

**Comment by lianshengxing** [comment]
@durs 
E:\wzh-projects\grgzpt\node_modules\._winax@0.2.3@winax>node "C:\Users\wzh-lian\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\\nod
e-gyp.js" rebuild
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\wzh-lian\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\wzh-lian\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npminstall\\node-gyp-bin\
\node-gyp.js" "rebuild"
gyp ERR! cwd E:\wzh-projects\grgzpt\node_modules\._winax@0.2.3@winax
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

err occured like  above

**Comment by yshyee** [comment]
@durs  Hello, i have the same question.
D:\electron_ws\t05\node-activex>node-gyp build 
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.1
gyp info using node@6.10.2 | win32 | x64
gyp info spawn C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\yan\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yan\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd D:\electron_ws\t05\node-activex
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok

**Comment by durs** [comment]
I have another version msbuild
C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe

See my log:
C:\Projects\_Durs\node-activex>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.9.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Сборка проектов в этом решении по одному. Чтобы включить параллельную
сборку, добавьте параметр "/m".
  utils.cpp
  win_delay_load_hook.cc
     Creating library
C:\Projects\_Durs\node-activex\build\Release\node_activex.lib and object
C:\Projects\_Durs\node-activex\build\Release\node_activex.exp
  Generating code
  Finished generating code
  node_activex.vcxproj ->
C:\Projects\_Durs\node-activex\build\Release\\node_activex.node
  node_activex.vcxproj ->
C:\Projects\_Durs\node-activex\build\Release\node_activex.pdb (Full PDB)
gyp info ok

2017-05-31 12:54 GMT+03:00 yshyee <notifications@github.com>:

**Comment by durs** [comment]
https://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64
