### ISSUE TITLE
Error: Loading non-context-aware native module in renderer

### ISSUE THREAD

**Issue by stilettk** [durs/node-activex#81]
After upgrading to Electron 9 i got the following error:
```
Error: Loading non-context-aware native module in renderer: '\\?\C:\Users\n.batov\AppData\Local\Temp\71a34dbd-f541-4157-a9e1-760b29018219.tmp.node', but app.allowRendererProcessReuse is true. See https://github.com/electron/electron/issues/18397.
```

I can change `app.allowRendererProcessReuse` to `false`, but it is said that in Electron v11 I shouldn't be able to use `node-activex` in it's current state.

**Comment by durs** [comment]
Hi, try the latest version 1.20

**Comment by stilettk** [comment]
Wow, that was fast! Yeah, it's working, thank you!
