### ISSUE TITLE
ocx methods call?

### ISSUE THREAD

**Issue by lucasjo** [durs/node-activex#83]
How to use ocx methods?

ocx is installed in the window.

var con = new ActiveXObject("xxxxx.xxxxx.1", { activate: true, async: true });
console.log(con)
print>
[Function: undefined] Dispatch {
  [__vars]: {},
  [__methods]: {
    ConnectServer: {
      name: 'ConnectServer',
      dispid: 1,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    GetQStatus: { name: 'GetQStatus', dispid: 2, invkind: 1, flags: 0, argcnt: 3 },
    IsConnected: { name: 'IsConnected', dispid: 3, invkind: 1, flags: 0, argcnt: 0 },
    DisconnectServer: {
      name: 'DisconnectServer',
      dispid: 4,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    Click2Call: { name: 'Click2Call', dispid: 5, invkind: 1, flags: 0, argcnt: 3 },
    SetLogMode: { name: 'SetLogMode', dispid: 6, invkind: 1, flags: 0, argcnt: 1 },
    SetEncryption: {
      name: 'SetEncryption',
      dispid: 7,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SendSIPCommand: {
      name: 'SendSIPCommand',
      dispid: 8,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    LoginBySWP: { name: 'LoginBySWP', dispid: 9, invkind: 1, flags: 0, argcnt: 3 },
    SetOamServerIP: {
      name: 'SetOamServerIP',
      dispid: 10,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    HangUp: { name: 'HangUp', dispid: 11, invkind: 1, flags: 0, argcnt: 0 },
    Answer: { name: 'Answer', dispid: 12, invkind: 1, flags: 0, argcnt: 0 },
    Transfer: { name: 'Transfer', dispid: 13, invkind: 1, flags: 0, argcnt: 1 },
    AtXfer: { name: 'AtXfer', dispid: 14, invkind: 1, flags: 0, argcnt: 1 },
    AtXferCID: { name: 'AtXferCID', dispid: 15, invkind: 1, flags: 0, argcnt: 2 },
    LoginServer: {
      name: 'LoginServer',
      dispid: 16,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    SetSeedEncryption: {
      name: 'SetSeedEncryption',
      dispid: 17,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    RemoteCall: { name: 'RemoteCall', dispid: 18, invkind: 1, flags: 0, argcnt: 4 },
    GetSettingInfo: {
      name: 'GetSettingInfo',
      dispid: 19,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SetAgentStatus: {
      name: 'SetAgentStatus',
      dispid: 20,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    QueueLogin: { name: 'QueueLogin', dispid: 21, invkind: 1, flags: 0, argcnt: 2 },
    QueueLogout: {
      name: 'QueueLogout',
      dispid: 22,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    QueueStatus: {
      name: 'QueueStatus',
      dispid: 23,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    HangUpDst: { name: 'HangUpDst', dispid: 24, invkind: 1, flags: 0, argcnt: 0 },
    HangUpChannel: {
      name: 'HangUpChannel',
      dispid: 25,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SetHeartBeat: {
      name: 'SetHeartBeat',
      dispid: 26,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SpyExten: { name: 'SpyExten', dispid: 27, invkind: 1, flags: 0, argcnt: 2 },
    SetForward: { name: 'SetForward', dispid: 28, invkind: 1, flags: 0, argcnt: 6 },
    StartRecord: {
      name: 'StartRecord',
      dispid: 29,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    StopRecord: { name: 'StopRecord', dispid: 30, invkind: 1, flags: 0, argcnt: 0 },
    SendSMS: { name: 'SendSMS', dispid: 31, invkind: 1, flags: 0, argcnt: 4 },
    SetUserInfo: {
      name: 'SetUserInfo',
      dispid: 32,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    GetPeerInfo: {
      name: 'GetPeerInfo',
      dispid: 33,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    GetCallHistory: {
      name: 'GetCallHistory',
      dispid: 34,
      invkind: 1,
      flags: 0,
      argcnt: 5
    },
    Hold: { name: 'Hold', dispid: 35, invkind: 1, flags: 0, argcnt: 0 },
    Unhold: { name: 'Unhold', dispid: 36, invkind: 1, flags: 0, argcnt: 0 },
    Pickup: { name: 'Pickup', dispid: 37, invkind: 1, flags: 0, argcnt: 1 },
    EncConnectServer: {
      name: 'EncConnectServer',
      dispid: 38,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    GetEncStr: { name: 'GetEncStr', dispid: 39, invkind: 1, flags: 0, argcnt: 1 },
    SetAutoReconnect: {
      name: 'SetAutoReconnect',
      dispid: 40,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SendPeerMsg: {
      name: 'SendPeerMsg',
      dispid: 41,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    RedirectConference: {
      name: 'RedirectConference',
      dispid: 42,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    InviteConference: {
      name: 'InviteConference',
      dispid: 43,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    RemoveConference: {
      name: 'RemoveConference',
      dispid: 44,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    JoinConference: {
      name: 'JoinConference',
      dispid: 45,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    GetStatusPeers: {
      name: 'GetStatusPeers',
      dispid: 46,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    GetBlindDtmf: {
      name: 'GetBlindDtmf',
      dispid: 47,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    GetRecordList: {
      name: 'GetRecordList',
      dispid: 48,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    CallWithConference: {
      name: 'CallWithConference',
      dispid: 49,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    MagAddrList: {
      name: 'MagAddrList',
      dispid: 50,
      invkind: 1,
      flags: 0,
      argcnt: 11
    },
    SetVarInfo: { name: 'SetVarInfo', dispid: 51, invkind: 1, flags: 0, argcnt: 3 },
    GetVarInfo: { name: 'GetVarInfo', dispid: 52, invkind: 1, flags: 0, argcnt: 1 },
    LoginByAdmin: {
      name: 'LoginByAdmin',
      dispid: 53,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    GetConfMemberList: {
      name: 'GetConfMemberList',
      dispid: 54,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    SetLoginType: {
      name: 'SetLoginType',
      dispid: 55,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    LoginBySWPMULTI: {
      name: 'LoginBySWPMULTI',
      dispid: 56,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    GetRecvSmsList: {
      name: 'GetRecvSmsList',
      dispid: 57,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    TalkAnswer: { name: 'TalkAnswer', dispid: 58, invkind: 1, flags: 0, argcnt: 1 },
    AboutBox: { name: 'AboutBox', dispid: -552, invkind: 1, flags: 0, argcnt: 0 }
  },
  [__type]: [
    {
      name: 'ConnectServer',
      dispid: 1,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    { name: 'GetQStatus', dispid: 2, invkind: 1, flags: 0, argcnt: 3 },
    { name: 'IsConnected', dispid: 3, invkind: 1, flags: 0, argcnt: 0 },
    {
      name: 'DisconnectServer',
      dispid: 4,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    { name: 'Click2Call', dispid: 5, invkind: 1, flags: 0, argcnt: 3 },
    { name: 'SetLogMode', dispid: 6, invkind: 1, flags: 0, argcnt: 1 },
    {
      name: 'SetEncryption',
      dispid: 7,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'SendSIPCommand',
      dispid: 8,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    { name: 'LoginBySWP', dispid: 9, invkind: 1, flags: 0, argcnt: 3 },
    {
      name: 'SetOamServerIP',
      dispid: 10,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    { name: 'HangUp', dispid: 11, invkind: 1, flags: 0, argcnt: 0 },
    { name: 'Answer', dispid: 12, invkind: 1, flags: 0, argcnt: 0 },
    { name: 'Transfer', dispid: 13, invkind: 1, flags: 0, argcnt: 1 },
    { name: 'AtXfer', dispid: 14, invkind: 1, flags: 0, argcnt: 1 },
    { name: 'AtXferCID', dispid: 15, invkind: 1, flags: 0, argcnt: 2 },
    {
      name: 'LoginServer',
      dispid: 16,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    {
      name: 'SetSeedEncryption',
      dispid: 17,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    { name: 'RemoteCall', dispid: 18, invkind: 1, flags: 0, argcnt: 4 },
    {
      name: 'GetSettingInfo',
      dispid: 19,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'SetAgentStatus',
      dispid: 20,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    { name: 'QueueLogin', dispid: 21, invkind: 1, flags: 0, argcnt: 2 },
    {
      name: 'QueueLogout',
      dispid: 22,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'QueueStatus',
      dispid: 23,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    { name: 'HangUpDst', dispid: 24, invkind: 1, flags: 0, argcnt: 0 },
    {
      name: 'HangUpChannel',
      dispid: 25,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'SetHeartBeat',
      dispid: 26,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    { name: 'SpyExten', dispid: 27, invkind: 1, flags: 0, argcnt: 2 },
    { name: 'SetForward', dispid: 28, invkind: 1, flags: 0, argcnt: 6 },
    {
      name: 'StartRecord',
      dispid: 29,
      invkind: 1,
      flags: 0,
      argcnt: 0
    },
    { name: 'StopRecord', dispid: 30, invkind: 1, flags: 0, argcnt: 0 },
    { name: 'SendSMS', dispid: 31, invkind: 1, flags: 0, argcnt: 4 },
    {
      name: 'SetUserInfo',
      dispid: 32,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'GetPeerInfo',
      dispid: 33,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'GetCallHistory',
      dispid: 34,
      invkind: 1,
      flags: 0,
      argcnt: 5
    },
    { name: 'Hold', dispid: 35, invkind: 1, flags: 0, argcnt: 0 },
    { name: 'Unhold', dispid: 36, invkind: 1, flags: 0, argcnt: 0 },
    { name: 'Pickup', dispid: 37, invkind: 1, flags: 0, argcnt: 1 },
    {
      name: 'EncConnectServer',
      dispid: 38,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    { name: 'GetEncStr', dispid: 39, invkind: 1, flags: 0, argcnt: 1 },
    {
      name: 'SetAutoReconnect',
      dispid: 40,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'SendPeerMsg',
      dispid: 41,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    {
      name: 'RedirectConference',
      dispid: 42,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'InviteConference',
      dispid: 43,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'RemoveConference',
      dispid: 44,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'JoinConference',
      dispid: 45,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'GetStatusPeers',
      dispid: 46,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'GetBlindDtmf',
      dispid: 47,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'GetRecordList',
      dispid: 48,
      invkind: 1,
      flags: 0,
      argcnt: 4
    },
    {
      name: 'CallWithConference',
      dispid: 49,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    {
      name: 'MagAddrList',
      dispid: 50,
      invkind: 1,
      flags: 0,
      argcnt: 11
    },
    { name: 'SetVarInfo', dispid: 51, invkind: 1, flags: 0, argcnt: 3 },
    { name: 'GetVarInfo', dispid: 52, invkind: 1, flags: 0, argcnt: 1 },
    {
      name: 'LoginByAdmin',
      dispid: 53,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    {
      name: 'GetConfMemberList',
      dispid: 54,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'SetLoginType',
      dispid: 55,
      invkind: 1,
      flags: 0,
      argcnt: 1
    },
    {
      name: 'LoginBySWPMULTI',
      dispid: 56,
      invkind: 1,
      flags: 0,
      argcnt: 3
    },
    {
      name: 'GetRecvSmsList',
      dispid: 57,
      invkind: 1,
      flags: 0,
      argcnt: 2
    },
    { name: 'TalkAnswer', dispid: 58, invkind: 1, flags: 0, argcnt: 1 },
    { name: 'AboutBox', dispid: -552, invkind: 1, flags: 0, argcnt: 0 }
  ],
  [__value]: [Circular],
  [__id]: 'Dispatch'
}

**Comment by durs** [comment]
Standard javascript invoking, such as
con.ConnectServer(host, port, user, password)
if (con.IsConnected()) {}

**Comment by lucasjo** [comment]
When I did the above, I got an error like below.
con.ConnectServer(
Error: DispInvoke: ConnectServer 오류입니다.

**Comment by lucasjo** [comment]
> Standard javascript invoking, such as
> con.ConnectServer(host, port, user, password)
> if (con.IsConnected()) {}

**Comment by GoodZivi** [comment]
> When I did the above, I got an error like below. con.ConnectServer( Error: DispInvoke: ConnectServer was Error.

Hi,lucas.
Have you solved it?I have the same question with you.
and it goes like
```
myObj.TestFun(1,5);
           ^
Error: DispInvoke: TestFun Catastrophic failure
```
