### ISSUE TITLE
Fail on heroku deployment

### ISSUE THREAD

**Issue by Lea-Reif** [durs/node-activex#85]
I have an API working with the package and it fails on heroku deployment. If anyone has seen this error, a little help is welcome.
`
remote:        > winax@1.20.0 install /tmp/build_4cbf9d27/node_modules/winax
remote:        > node-gyp rebuild
remote:
remote:        make: Entering directory '/tmp/build_4cbf9d27/node_modules/winax/build'
remote:          CXX(target) Release/obj.target/node_activex/src/main.o
remote:        In file included from ../src/main.cpp:7:0:
remote:        ../src/stdafx.h:3:10: fatal error: SDKDDKVer.h: No such file or directory
remote:         #include <SDKDDKVer.h>
remote:                  ^~~~~~~~~~~~~
remote:        compilation terminated.
remote:        node_activex.target.mk:111: recipe for target 'Release/obj.target/node_activex/src/main.o' failed
remote:        make: *** [Release/obj.target/node_activex/src/main.o] Error 1
remote:        make: Leaving directory '/tmp/build_4cbf9d27/node_modules/winax/build'
remote:        gyp ERR! build error
remote:        gyp ERR! stack Error: `make` failed with exit code: 2
remote:        gyp ERR! stack     at ChildProcess.onExit (/tmp/build_4cbf9d27/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
remote:        gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
remote:        gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
remote:        gyp ERR! System Linux 4.4.0-1078-aws
remote:        gyp ERR! command "/tmp/build_4cbf9d27/.heroku/node/bin/node" "/tmp/build_4cbf9d27/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
remote:        gyp ERR! cwd /tmp/build_4cbf9d27/node_modules/winax
remote:        gyp ERR! node -v v12.19.0
remote:        gyp ERR! node-gyp -v v5.1.0
remote:        gyp ERR! not ok
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! winax@1.20.0 install: `node-gyp rebuild`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the winax@1.20.0 install script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.5H0t3/_logs/2020-10-20T20_23_31_370Z-debug.log
remote:
remote: -----> Build failed
remote:  `

**Comment by durs** [comment]
winax for win32 os only

**Comment by Lea-Reif** [comment]
> winax for win32 os only

There is not another similar package?

**Comment by durs** [comment]
No and can't be, COM/ActiveX libraries work only in the win32 environment

вс, 25 окт. 2020 г. в 22:50, Manuel Guzmán <notifications@github.com>:

**Comment by Lea-Reif** [comment]
Thanks
