### ISSUE TITLE
some err with 'node-gyp.js'

### ISSUE THREAD

**Issue by lianshengxing** [durs/node-activex#9]
i executed the command 'npm install winax',and then installed1packages,but it threw err as below
'E:\wzh-projects\grgzpt\node_modules._winax@0.2.3@winax>node "C:\Users\wzh-lian\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin\nod
e-gyp.js" rebuild
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\wzh-lian\AppData\Roaming\npm\node_modules\cnpm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\wzh-lian\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\node-gyp-bin
\node-gyp.js" "rebuild"
gyp ERR! cwd E:\wzh-projects\grgzpt\node_modules._winax@0.2.3@winax
gyp ERR! node -v v6.10.2
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok'
then i required winax in electron-vue ,it threw an err that 'can not find module './build/Release/node_activex'

**Comment by durs** [comment]
Need VC++ 2013, 2015, 2017
But used C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
May be ... npm config set msvs_version 2015 --global
See https://stackoverflow.com/questions/21562038/node-gyp-build-error-windows-x64

**Comment by durs** [comment]
My commands log
C:\Projects\_Durs\node-activex>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@7.9.0 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
  utils.cpp
  win_delay_load_hook.cc
     Creating library C:\Projects\_Durs\node-activex\build\Release\node_activex.lib and object C:\Projects\_Durs\node-activex\build\Release\node_activex.exp
  Generating code
  Finished generating code
  node_activex.vcxproj -> C:\Projects\_Durs\node-activex\build\Release\\node_activex.node
  node_activex.vcxproj -> C:\Projects\_Durs\node-activex\build\Release\node_activex.pdb (Full PDB)
gyp info ok

**Comment by lianshengxing** [comment]
@durs 
i execused the command that 'npm config set msvs_version 2015 --global',and i have build the 'windows-build-tools', but it still threw err that 'ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1'

**Comment by lianshengxing** [comment]
excuse me , i executed the command 'npm install winax' and have successfully install the winax, but when i require it in my project,it threw an err that ' Error: A dynamic link library (DLL) initialization routine failed.
          \\?\E:\wzh-projects\grgzpt\node_modules\._winax@0.2.3@winax\build\Release\node_activex.node',

could you help me ?thanks a lot

**Comment by durs** [comment]
Because the module 'node_activex.node' must be compiled during installation.
Or this file exists in the folder?

2017-06-01 4:24 GMT+03:00 lianshengxing <notifications@github.com>:

**Comment by lianshengxing** [comment]
@durs 
what should i do to fix it ,i just dont know the reason for this err
