### ISSUE TITLE
Compiling node native addons against this project

### ISSUE THREAD

**Issue by Daniel-Userlane** [durs/node-activex#97]
Hey guys,

Thanks for your work on this npm package!
I'm currently developing a custom native ode addon and would like to use your translations from VARIANT to the respective JS types.
Apparently the best way to do this would be if you could add another gyp file (or just an extra target) with a library configuration,

eg. like this:

```
{
  'target_name': 'lib_node_activex',
  'type': 'static_library',
  'sources': [
    'src/utils.cpp',
    'src/disp.cpp'
  ],
  'direct_dependent_settings': {
    'include_dirs': ['.']
  },
  'dependencies': [
  ]
}
```

as then linking against this library is possible with:
```
"dependencies": [
  "<!(node -p \"require.resolve('winax/binding.gyp')\"):lib_node_activex"
],
```

Would this be possible or do you have any other suggestion for how to implement this?

Thanks,
Daniel

**Comment by durs** [comment]
Hi, I did it according to your example

**Comment by Daniel-Userlane** [comment]
Oh wow, that was faster than expected ^^
Thanks a lot!

Can you please try to make sure that your build still works as expected?
(I don't wanna accidentally break this for other people)

One thing that would make this even greater for library usage would be a .h file that is easy to include with a very specific naming so it doesn't conflict with any other packages.
But I'm not certain how much extra effort that would be for you.

eg. `node_activex.h`
```cpp
#pragma once

#include "src/stdafx.h"
#include "src/utils.h"
#include "src/disp.h"
```

that lies in the root folder so as the `'include_dirs'` points to `'.'`, this should make it possible to simply include
`#include <node_activex.h>`

But let me test this out tomorrow first so I don't make any stupid mistakes here.

If you want me to, I can also create a PR for this together with a Readme description so other people know how to use this

**Comment by Daniel-Userlane** [comment]
Also I realized namespaces would be a great thing to not spam the global namespace when importing (esp. with all the using namespace directives) but doing a bit of research I learned that that would require quite a bit of rework on the code...

Probably not something you'd be willing to put effort into, I assume?
Would you be ok with me restructuring the code for that if I find time in the next weeks?

**Comment by durs** [comment]
It would be nice if you did it yourself

пн, 28 июн. 2021 г. в 00:55, Daniel-Userlane ***@***.***>:
